variable "project_name" {
  description = "Short, lowercase identifier for the DDMS deployment (used as a prefix for named resources)."
  type        = string
}

variable "environment" {
  description = "Environment tag applied to provisioned resources (e.g. dev, staging, prod)."
  type        = string
}

variable "aws_region" {
  description = "AWS region where the infrastructure will be created."
  type        = string
  default     = "us-east-1"
}

variable "vpc_cidr" {
  description = "CIDR block for the VPC hosting the ECS cluster."
  type        = string
  default     = "10.42.0.0/16"
}

variable "public_subnet_cidrs" {
  description = "List of CIDR blocks for public subnets (tasks receive public IPs)."
  type        = list(string)
  default     = ["10.42.0.0/20", "10.42.16.0/20"]
}

variable "container_port" {
  description = "Container port exposed by the Fastify API."
  type        = number
  default     = 3001
}

variable "desired_count" {
  description = "Number of ECS tasks the service should maintain."
  type        = number
  default     = 2
}

variable "container_cpu" {
  description = "CPU units for the ECS task definition (1024 == 1 vCPU)."
  type        = number
  default     = 512
}

variable "container_memory" {
  description = "Memory (in MiB) allocated to the ECS task definition."
  type        = number
  default     = 1024
}

variable "container_image_tag" {
  description = "Image tag to deploy from the ECR repository."
  type        = string
  default     = "latest"
}

variable "supabase_db_url" {
  description = "Supabase PostgreSQL connection string used by the API (format: postgresql://...)."
  type        = string
  sensitive   = true
}

variable "supabase_db_secret_name" {
  description = "Name to apply to the Secrets Manager secret containing the Supabase connection string."
  type        = string
  default     = ""
}

variable "log_retention_in_days" {
  description = "Retention period for CloudWatch Logs generated by the ECS tasks."
  type        = number
  default     = 30
}

variable "health_check_path" {
  description = "HTTP path used by the load balancer to probe container health."
  type        = string
  default     = "/health"
}

variable "web_container_port" {
  description = "Container port exposed by the Next.js web application."
  type        = number
  default     = 3000
}

variable "web_desired_count" {
  description = "Number of ECS tasks to run for the web application."
  type        = number
  default     = 2
}

variable "web_container_cpu" {
  description = "CPU units allocated to the web application task definition (1024 == 1 vCPU)."
  type        = number
  default     = 512
}

variable "web_container_memory" {
  description = "Memory (in MiB) allocated to the web application task definition."
  type        = number
  default     = 1024
}

variable "web_container_image_tag" {
  description = "Image tag to deploy from the web ECR repository."
  type        = string
  default     = "latest"
}

variable "web_health_check_path" {
  description = "HTTP path used by the load balancer to probe the web container health."
  type        = string
  default     = "/"
}

variable "web_next_public_api_base_path" {
  description = "API path appended to the ALB host when setting NEXT_PUBLIC_API_BASE_URL for the web container."
  type        = string
  default     = "/api/v1"
}

variable "web_next_public_tenant_id" {
  description = "Default tenant identifier exposed to the web application."
  type        = string
  default     = "11111111-1111-1111-1111-111111111111"
}

variable "web_next_public_dev_jwt" {
  description = "Development JWT forwarded by the web application when talking to the API."
  type        = string
  default     = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkZXYtdXNlciIsInJvbGVzIjpbImFkbWluIl0sInRlbmFudF9pZCI6IjExMTExMTExLTExMTEtMTExMS0xMTExLTExMTExMTExMTExMSJ9.6HPdCV5lI1DUoGLrQa4u0pgdOZW86CPZta6s5Z7ZPBk"
}
