/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/entity-types": {
    /**
     * List Entity Types
     * @description Retrieves a list of all entity types for the tenant.
     */
    get: operations["listEntityTypes"];
    /**
     * Create Entity Type
     * @description Creates a new entity type.
     */
    post: operations["createEntityType"];
  };
  "/entity-types/{entityTypeId}": {
    /**
     * Update Entity Type
     * @description Updates an existing entity type.
     */
    patch: operations["updateEntityType"];
  };
  "/entity-types/{entityTypeId}/fields": {
    /**
     * List Field Definitions
     * @description Retrieves a list of all field definitions for a given entity type.
     */
    get: operations["listFieldDefs"];
    /**
     * Create Field Definition
     * @description Creates a new field definition for an entity type.
     */
    post: operations["createFieldDef"];
  };
  "/entities/{entityTypeKey}": {
    /**
     * Create Record
     * @description Creates a new record for a given entity type.
     */
    post: operations["createRecord"];
  };
  "/entities/{entityTypeKey}/search": {
    /**
     * Search Records
     * @description Searches for records of a given entity type using a filter.
     */
    post: operations["searchRecords"];
  };
  "/entities/{entityTypeKey}/{recordId}": {
    /**
     * Get Record by ID
     * @description Retrieves a single record by its ID.
     */
    get: operations["getRecord"];
    /**
     * Update Record
     * @description Updates an existing record. Uses optimistic locking via a version number.
     */
    patch: operations["updateRecord"];
  };
  "/fields/{fieldId}": {
    /**
     * Update Field Definition
     * @description Updates an existing field definition.
     */
    patch: operations["updateFieldDef"];
  };
  "/relations": {
    /**
     * List Relations
     * @description Retrieves a list of relations, typically filtered by the source record and field.
     */
    get: operations["listRelations"];
    /**
     * Create Relation
     * @description Creates a new relationship (edge) between two records.
     */
    post: operations["createRelation"];
  };
  "/relations/{relationId}": {
    /**
     * Delete Relation
     * @description Deletes an existing relationship (edge).
     */
    delete: operations["deleteRelation"];
  };
  "/indexes": {
    /**
     * List Field Index Jobs
     * @description Retrieves the status of field indexing jobs for the current tenant.
     */
    get: operations["listFieldIndexes"];
  };
  "/events": {
    /**
     * Subscribe to real-time events
     * @description Establishes a Server-Sent Events (SSE) connection to receive real-time updates for the current tenant.
     */
    get: operations["subscribeToEvents"];
  };
  "/audit/activity-log": {
    /**
     * List Activity Events
     * @description Returns recent audit log events for the tenant, ordered with the latest first.
     */
    get: operations["listActivityLog"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    EntityType: {
      /** Format: uuid */
      id: string;
      /** @description A unique machine-readable key for the entity type (e.g., "user", "project"). */
      key: string;
      /** @description A human-readable label for the entity type (e.g., "User", "Project"). */
      label: string;
      /** @description A description of the entity type. */
      description?: string | null;
    };
    EntityTypeCreate: {
      /** @description A unique machine-readable key for the entity type (e.g., "user", "project"). */
      key: string;
      /** @description A human-readable label for the entity type (e.g., "User", "Project"). */
      label: string;
      /** @description A description of the entity type. */
      description?: string | null;
    };
    EntityTypeUpdate: {
      /** @description A human-readable label for the entity type (e.g., "User", "Project"). */
      label?: string;
      /** @description A description of the entity type. */
      description?: string | null;
    };
    FieldDef: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      entityTypeId: string;
      /** @description A unique machine-readable key for the field (e.g., "status", "budget"). */
      key: string;
      /** @description A human-readable label for the field (e.g., "Status", "Budget"). */
      label: string;
      /** @enum {string} */
      kind: "text" | "number" | "date" | "select" | "relation" | "boolean";
      /** @default false */
      required?: boolean;
      /** @default false */
      uniqueWithinType?: boolean;
      /** @default true */
      searchable?: boolean;
      /** @default false */
      indexed?: boolean;
      options?: components["schemas"]["FieldDefOptions"];
      validate?: components["schemas"]["FieldDefValidate"];
      acl?: components["schemas"]["FieldDefAcl"];
      /** @default 0 */
      position?: number;
      /** @default true */
      active?: boolean;
    };
    FieldDefCreate: {
      key: string;
      label: string;
      /** @enum {string} */
      kind: "text" | "number" | "date" | "select" | "relation" | "boolean";
      required?: boolean;
      uniqueWithinType?: boolean;
      searchable?: boolean;
      indexed?: boolean;
      options?: components["schemas"]["FieldDefOptions"];
      validate?: components["schemas"]["FieldDefValidate"];
      acl?: components["schemas"]["FieldDefAcl"];
      position?: number;
    };
    FieldDefUpdate: {
      label?: string;
      required?: boolean;
      uniqueWithinType?: boolean;
      searchable?: boolean;
      indexed?: boolean;
      options?: components["schemas"]["FieldDefOptions"];
      validate?: components["schemas"]["FieldDefValidate"];
      acl?: components["schemas"]["FieldDefAcl"];
      position?: number;
      active?: boolean;
    };
    FieldDefOptions: {
      /** @description For kind="select". A list of possible values. */
      enum?: string[];
      /** @description For kind="select". Whether multiple values can be selected. */
      multiselect?: boolean;
      /** @description For kind="relation". Defines the relationship target. */
      relation?: {
        /** Format: uuid */
        targetEntityTypeId: string;
        /** @enum {string} */
        cardinality: "one" | "many";
      };
      /**
       * @description For computed fields. An expression to calculate the field value.
       * @example price * qty
       */
      formula?: string;
      /** @description Conditional visibility rules for the UI. */
      visibleIf?: Record<string, never>[];
      /** @description Conditional requirement rules. */
      requiredIf?: Record<string, never>[];
    };
    /** @description Validation rules that depend on the field kind. */
    FieldDefValidate: {
      text?: {
        minLen?: number;
        maxLen?: number;
        regex?: string;
      };
      number?: {
        min?: number;
        max?: number;
        integer?: boolean;
      };
      date?: {
        /** Format: date */
        min?: string;
        /** Format: date */
        max?: string;
      };
    };
    /** @description Access control list defining roles for read/write access. */
    FieldDefAcl: {
      read?: string[];
      write?: string[];
    };
    Record: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      entityTypeId: string;
      /** @description The version number of the record, used for optimistic locking. */
      version: number;
      /**
       * @description A JSON object containing the custom field data for the record.
       * @example {
       *   "name": "AI Roadmap Q4",
       *   "status": "Active",
       *   "budget": 12000
       * }
       */
      data: {
        [key: string]: unknown;
      };
      /** Format: uuid */
      createdBy?: string | null;
      /** Format: uuid */
      updatedBy?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    RecordCreate: {
      /** @description A JSON object containing the custom field data for the new record. */
      data: {
        [key: string]: unknown;
      };
    };
    RecordUpdate: {
      /** @description A JSON object containing the fields to update. */
      data: {
        [key: string]: unknown;
      };
      /** @description The current version of the record being updated, for optimistic locking. */
      version: number;
    };
    ActivityCategory: "schema" | "record" | "governance" | "import" | "integration";
    AuditLogEvent: {
      id: number;
      occurredAt: string;
      action: string;
      category: components["schemas"]["ActivityCategory"];
      actorId?: string | null;
      actorLabel?: string | null;
      resourceType: string;
      resourceId?: string | null;
      meta: {
        [key: string]: unknown;
      };
    };
    ActivityLogSummary: {
      totalEvents: number;
      schemaEdits: number;
      recordUpdates: number;
      uniqueActors: number;
      lastEventAt?: string | null;
    };
    ActivityLogResponse: {
      events: components["schemas"]["AuditLogEvent"][];
      summary: components["schemas"]["ActivityLogSummary"];
    };
    Relation: {
      /** Format: uuid */
      id: string;
      /**
       * Format: uuid
       * @description The ID of the relation field definition.
       */
      field_id: string;
      /**
       * Format: uuid
       * @description The ID of the source record in the relation.
       */
      from_record_id: string;
      /**
       * Format: uuid
       * @description The ID of the target record in the relation.
       */
      to_record_id: string;
      /** Format: uuid */
      createdBy?: string | null;
      /** Format: date-time */
      createdAt: string;
    };
    RelationWithContext: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      field_id: string;
      /** Format: uuid */
      from_record_id: string;
      /** Format: uuid */
      to_record_id: string;
      /** Format: uuid */
      createdBy?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** @enum {string} */
      direction: "from" | "to";
      field: {
        /** Format: uuid */
        id: string;
        key: string;
        label: string;
        /** Format: uuid */
        entityTypeId: string;
        /** Format: uuid */
        targetEntityTypeId?: string | null;
        /** @enum {string} */
        cardinality?: "one" | "many" | null;
      };
      relatedRecord: {
        /** Format: uuid */
        id: string;
        /** Format: uuid */
        entityTypeId: string;
        label?: string | null;
      };
    };
    RelationCreate: {
      /**
       * Format: uuid
       * @description The ID of the relation field definition.
       */
      field_id: string;
      /**
       * Format: uuid
       * @description The ID of the source record in the relation.
       */
      from_record_id: string;
      /**
       * Format: uuid
       * @description The ID of the target record in the relation.
       */
      to_record_id: string;
    };
    FieldIndexJob: {
      /** Format: uuid */
      id: string;
      /** Format: uuid */
      fieldId: string;
      /** Format: uuid */
      entityTypeId: string;
      indexName: string;
      /** @enum {string} */
      status: "pending" | "in_progress" | "ready" | "failed";
      attempts: number;
      lastError?: string | null;
      /** Format: date-time */
      startedAt?: string | null;
      /** Format: date-time */
      completedAt?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      fieldKey: string;
      fieldLabel: string;
    };
    SearchRequest: {
      filter?: components["schemas"]["Filter"];
      /** @description An array of sort objects to apply to the results. */
      sort?: components["schemas"]["Sort"][];
      /**
       * @description The maximum number of records to return.
       * @default 50
       */
      limit?: number;
      /** @description A cursor for pagination, obtained from a previous search response. */
      cursor?: string | null;
    };
    SearchResponse: {
      rows: components["schemas"]["Record"][];
      /** @description A cursor to retrieve the next page of results. Null if there are no more results. */
      nextCursor?: string | null;
      /** @description The total number of records matching the filter. */
      total: number;
    };
    Sort: {
      /** @description The key of the field to sort by (e.g., "budget", "createdAt"). */
      field: string;
      /**
       * @default asc
       * @enum {string}
       */
      dir?: "asc" | "desc";
    };
    /**
     * @description A flexible filter object to query records. It can be a logical operator (`and`, `or`, `not`) or a field-level comparison.
     * See the manifest for the full grammar.
     *
     * @example {
     *   "op": "and",
     *   "filters": [
     *     {
     *       "op": "eq",
     *       "field": "status",
     *       "value": "Active"
     *     },
     *     {
     *       "op": "gte",
     *       "field": "budget",
     *       "value": 10000
     *     },
     *     {
     *       "op": "fulltext",
     *       "query": "ai roadmap"
     *     }
     *   ]
     * }
     */
    Filter: {
      /** @description The operator for the filter. */
      op?: string;
      /** @description Used with logical operators `and` and `or`. */
      filters?: components["schemas"]["Filter"][];
      /** @description The key of the field to compare. */
      field?: string;
      /** @description The value to compare against. */
      value?: unknown;
      /** @description An array of values for the `in` operator. */
      values?: unknown[];
      /** @description The search query for `fulltext` search. */
      query?: string;
    };
    Error: {
      /**
       * @description A machine-readable error code.
       * @example VALIDATION_ERROR
       */
      code: string;
      /**
       * @description A human-readable error message.
       * @example The request body is invalid.
       */
      message: string;
      /**
       * Format: uuid
       * @description A unique identifier for the request, useful for tracing.
       */
      requestId?: string;
      errors?: components["schemas"]["ValidationErrorDetail"][];
    };
    ValidationErrorDetail: {
      /**
       * @description The path to the invalid field in the request body.
       * @example budget
       */
      path: string;
      /**
       * @description A machine-readable code for the specific validation error.
       * @example too_small
       */
      code: string;
      /**
       * @description A human-readable message for the specific validation error.
       * @example The budget must be at least 0.
       */
      message: string;
    };
  };
  responses: {
    /** @description Bad Request - The request body is invalid. */
    BadRequest: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Not Found - The requested resource does not exist. */
    NotFound: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Conflict - The request could not be completed due to a conflict with the current state of the resource, likely an optimistic locking failure. */
    Conflict: {
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    /** @description The ID of the entity type. */
    entityTypeId: string;
    /** @description The unique machine-readable key for the entity type (e.g., "user", "project"). */
    entityTypeKey: string;
    /** @description The ID of the record. */
    recordId: string;
    /** @description The ID of the field definition. */
    fieldId: string;
    /** @description The ID of the relation (edge). */
    relationId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * List Entity Types
   * @description Retrieves a list of all entity types for the tenant.
   */
  listEntityTypes: {
    responses: {
      /** @description A list of entity types. */
      200: {
        content: {
          "application/json": components["schemas"]["EntityType"][];
        };
      };
    };
  };
  /**
   * Create Entity Type
   * @description Creates a new entity type.
   */
  createEntityType: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["EntityTypeCreate"];
      };
    };
    responses: {
      /** @description Entity type created successfully. */
      201: {
        content: {
          "application/json": components["schemas"]["EntityType"];
        };
      };
      400: components["responses"]["BadRequest"];
    };
  };
  /**
   * Update Entity Type
   * @description Updates an existing entity type.
   */
  updateEntityType: {
    parameters: {
      path: {
        entityTypeId: components["parameters"]["entityTypeId"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["EntityTypeUpdate"];
      };
    };
    responses: {
      /** @description Entity type updated successfully. */
      200: {
        content: {
          "application/json": components["schemas"]["EntityType"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * List Field Definitions
   * @description Retrieves a list of all field definitions for a given entity type.
   */
  listFieldDefs: {
    parameters: {
      path: {
        entityTypeId: components["parameters"]["entityTypeId"];
      };
    };
    responses: {
      /** @description A list of field definitions. */
      200: {
        content: {
          "application/json": components["schemas"]["FieldDef"][];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Create Field Definition
   * @description Creates a new field definition for an entity type.
   */
  createFieldDef: {
    parameters: {
      path: {
        entityTypeId: components["parameters"]["entityTypeId"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FieldDefCreate"];
      };
    };
    responses: {
      /** @description Field definition created successfully. */
      201: {
        content: {
          "application/json": components["schemas"]["FieldDef"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Create Record
   * @description Creates a new record for a given entity type.
   */
  createRecord: {
    parameters: {
      path: {
        entityTypeKey: components["parameters"]["entityTypeKey"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecordCreate"];
      };
    };
    responses: {
      /** @description Record created successfully. */
      201: {
        content: {
          "application/json": components["schemas"]["Record"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Search Records
   * @description Searches for records of a given entity type using a filter.
   */
  searchRecords: {
    parameters: {
      path: {
        entityTypeKey: components["parameters"]["entityTypeKey"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SearchRequest"];
      };
    };
    responses: {
      /** @description A list of matching records. */
      200: {
        content: {
          "application/json": components["schemas"]["SearchResponse"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Get Record by ID
   * @description Retrieves a single record by its ID.
   */
  getRecord: {
    parameters: {
      path: {
        entityTypeKey: components["parameters"]["entityTypeKey"];
        recordId: components["parameters"]["recordId"];
      };
    };
    responses: {
      /** @description The requested record. */
      200: {
        content: {
          "application/json": components["schemas"]["Record"];
        };
      };
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Update Record
   * @description Updates an existing record. Uses optimistic locking via a version number.
   */
  updateRecord: {
    parameters: {
      path: {
        entityTypeKey: components["parameters"]["entityTypeKey"];
        recordId: components["parameters"]["recordId"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecordUpdate"];
      };
    };
    responses: {
      /** @description Record updated successfully. */
      200: {
        content: {
          "application/json": components["schemas"]["Record"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      409: components["responses"]["Conflict"];
    };
  };
  /**
   * Update Field Definition
   * @description Updates an existing field definition.
   */
  updateFieldDef: {
    parameters: {
      path: {
        fieldId: components["parameters"]["fieldId"];
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["FieldDefUpdate"];
      };
    };
    responses: {
      /** @description Field definition updated successfully. */
      200: {
        content: {
          "application/json": components["schemas"]["FieldDef"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * List Relations
   * @description Retrieves relations for a record, optionally filtered by field and direction.
   */
  listRelations: {
    parameters: {
      query: {
        /** @description The record to use when searching for relations. */
        record_id: string;
        /** @description Whether to return relations where the record is the source (`from`) or target (`to`). */
        role?: "from" | "to";
        /** @description If provided, limits results to a specific relation field. */
        field_id?: string;
      };
    };
    responses: {
      /** @description A list of relations. */
      200: {
        content: {
          "application/json": components["schemas"]["RelationWithContext"][];
        };
      };
      400: components["responses"]["BadRequest"];
    };
  };
  /**
   * Create Relation
   * @description Creates a new relationship (edge) between two records.
   */
  createRelation: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RelationCreate"];
      };
    };
    responses: {
      /** @description Relation created successfully. */
      201: {
        content: {
          "application/json": components["schemas"]["Relation"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * Delete Relation
   * @description Deletes an existing relationship (edge).
   */
  deleteRelation: {
    parameters: {
      path: {
        relationId: components["parameters"]["relationId"];
      };
    };
    responses: {
      /** @description Relation deleted successfully. */
      204: {
        content: never;
      };
      404: components["responses"]["NotFound"];
    };
  };
  /**
   * List Field Index Jobs
   * @description Retrieves the status of field indexing jobs for the current tenant.
   */
  listFieldIndexes: {
    responses: {
      /** @description A list of field index jobs. */
      200: {
        content: {
          "application/json": components["schemas"]["FieldIndexJob"][];
        };
      };
    };
  };
  /**
   * Subscribe to real-time events
   * @description Establishes a Server-Sent Events (SSE) connection to receive real-time updates for the current tenant.
   */
  subscribeToEvents: {
    responses: {
      /** @description SSE connection established. */
      200: {
        content: {
          "text/event-stream": unknown;
        };
      };
    };
  };
  /**
   * List Activity Events
   * @description Returns recent audit log events for the tenant, ordered with the latest first.
   */
  listActivityLog: {
    parameters: {
      query?: {
        limit?: number;
        cursor?: string;
        type?: components["schemas"]["ActivityCategory"];
        search?: string;
      };
    };
    responses: {
      /** @description A list of activity events. */
      200: {
        content: {
          "application/json": components["schemas"]["ActivityLogResponse"];
        };
      };
    };
  };
}
